version: '3'
services:
  frontend:
    build: 
      context: ./ms-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  apigateway:
    build: 
      context: ./ms-apigateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./ms-apigateway/.env
  flask:
    build: 
      context: ./ms-flask
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
  go:
    build: 
      context: ./ms-go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
