FROM python:3.7-alpine

LABEL maintainer="mc222sn@student.lnu.se"
LABEL version="1.0"
LABEL description="Flask app"

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt

CMD [ "python", "./src/app.py" ]
