apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nginx
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - image: mjovanc/ms-frontend:1.0
        name: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: Always
