FROM golang:latest

LABEL maintainer="mc222sn@student.lnu.se"
LABEL version="1.0"
LABEL description="Go (golang) app"

RUN go get -u github.com/gorilla/mux

WORKDIR /go/src/app
ADD src src

CMD ["go", "run", "src/index.go"]
