version: '3'

services:
  frontend:
    build:
      context: ./ms-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./ms-frontend:/src/app
    ports:
      - "80:80"
  apigateway:
    build:
      context: ./ms-apigateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./ms-apigateway:/src/app
    ports:
      - "5000:5000"
    env_file:
      - ./ms-apigateway/.env
  flask:
    build:
      context: ./ms-flask
      dockerfile: Dockerfile.dev
    volumes:
      - ./ms-flask:/src/app
    ports:
      - "6000:6000"
  go:
    build:
      context: ./ms-go
      dockerfile: Dockerfile.dev
    volumes:
      - ./ms-go:/src/app
    ports:
      - "8080:8080"
  redis:
    image: 'redis'
    container_name: database
    expose:
      - 6379
  node:
    build:
      context: ./ms-node
      dockerfile: Dockerfile.dev
    volumes:
      - ./ms-node:/src/app
    ports:
      - "4000:4000"
    links:
      - redis
    environment:
      - REDIS_URL=redis://database
